### ISSUE TITLE
Не могу ввести пароль

### ISSUE THREAD

**Issue by vVSamurayVv** [LuigiVampa92/vk_sender#1]
Запускаю скрипт, пишу auth, ввожу логин, а пароль ввести не получается, т.е. символы не печатаются вообще. Я тут новичок, так что извините если тупой вопрос

**Comment by LuigiVampa92** [comment]
> Запускаю скрипт, пишу auth, ввожу логин, а пароль ввести не получается, т.е. символы не печатаются вообще. Я тут новичок, так что извините если тупой вопрос

Привет. Символы вводятся, просто не отображаются. Сделано это для того чтобы нельзя было подсмотреть количество введённых символов (логика та же что и при вводе паролей в терминале в линуксах)
